[2023-08-08T15:53:58.000-0300] {processor.py:157} INFO - Started process (PID=6267) to work on /home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-08T15:53:58.001-0300] {processor.py:826} INFO - Processing file /home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-08T15:53:58.002-0300] {logging_mixin.py:150} INFO - [2023-08-08T15:53:58.001-0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-08T15:53:58.006-0300] {logging_mixin.py:150} INFO - [2023-08-08T15:53:58.006-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-08T15:53:58.007-0300] {logging_mixin.py:150} INFO - [2023-08-08T15:53:58.007-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-08T15:53:58.007-0300] {processor.py:838} WARNING - No viable dags retrieved from /home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-08T15:53:58.022-0300] {processor.py:179} INFO - Processing /home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-08-08T15:55:31.715-0300] {processor.py:157} INFO - Started process (PID=6767) to work on /home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-08T15:55:31.716-0300] {processor.py:826} INFO - Processing file /home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-08T15:55:31.716-0300] {logging_mixin.py:150} INFO - [2023-08-08T15:55:31.716-0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-08T15:55:31.719-0300] {logging_mixin.py:150} INFO - [2023-08-08T15:55:31.718-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-08T15:55:31.719-0300] {logging_mixin.py:150} INFO - [2023-08-08T15:55:31.719-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-08T15:55:31.719-0300] {processor.py:838} WARNING - No viable dags retrieved from /home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-08T15:55:31.728-0300] {processor.py:179} INFO - Processing /home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
